# NumPy Exercises

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

This is the version without solutions. If you're a lonely wolf or not participating to this lecture, feel free to give it a try!

In [1]:
import numpy as np
import numba as nb
import sys

print("Python version: {0}\n"
      "NumPy version: {1}\n"
      "numba version: {2}"
      .format(sys.version, np.__version__, nb.__version__))

Python version: 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:07:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy version: 1.17.3
numba version: 0.41.0


In [2]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "ndim: {o.ndim}\n"
          "shape: {o.shape}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

In [3]:
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## Exercise 1: Create a 5x5 matrix with 5's on its diagonal

```5 0 0 0 0
0 5 0 0 0
0 0 5 0 0
0 0 0 5 0
0 0 0 0 5
```

In [5]:
np.eye(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

## Exercise 2: Create a random array with 10 elements and replace its largest value with 0

In [12]:
a = np.random.random(10)
a[np.argmax(a)]


0.8738270491919315

## Exercise 3: Create the following array

    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5


## Exercise 4: Create a checkerboard (8x8, 0s and 1s)

    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0

## Exercise 5: Extract the integer part of a random sample

    np.random.uniform(0, 10, 10)
    
e.g. `[23.5, 42.0, 500.3, 123.9] -> [23, 42, 500, 123]`

In [20]:
a = np.random.uniform(0, 10, 10)
a - a % 1

array([8., 4., 0., 1., 6., 7., 9., 4., 7., 1.])

## Exercise 6: Create an array with 10 equidistant numbers between 0 and 1, excluding 0 and 1

In [22]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## Exercise 7: Find the value closest to a given number in an array

    a = np.random.random(10)
    target = 0.23

In [25]:
a = np.random.random(10)
target = 0.23
print(a)
a[np.argmin(np.abs(a - target))]

[0.10180504 0.92388563 0.68391529 0.16029242 0.61443178 0.3686321
 0.41395696 0.46493936 0.18522585 0.96147069]


0.18522585497245292

## Exercise 8: Multiply two arrays elementwise

    a = np.random.random(1234567)
    b = np.random.random(1234567)

In [26]:
a = np.random.random(1234567)
b = np.random.random(1234567)
a*b

array([0.36404541, 0.15333669, 0.31938671, ..., 0.27962357, 0.53908674,
       0.12332111])

## Exercise 9: Calculate the cosine of 12.345.678 elements

    a = np.random.random(12345678)

In [27]:
a = np.random.random(12345678)
np.cos(a)

array([0.99960853, 0.78162422, 0.58555515, ..., 0.9645497 , 0.72727277,
       0.97628671])

## Exercise 10: Calculate the following, with two 1.234.567 length arrays:

    a = np.random.random(1234567)
    b = np.random.random(1234567)
    
$$
c_i = \tan(a_i) \cdot b_i - a_i^{b_i}
$$

for $i \in [0, 1234566]$

In [28]:
a = np.random.random(1234567)
b = np.random.random(1234567)
np.tan(a) * b - a**b

array([-0.1653243 , -0.09561715, -0.25429689, ..., -0.6272589 ,
       -0.47931886, -0.32131564])

### What about a Python loop?

    a = np.random.random(1234567)
    b = np.random.random(1234567)
    
$$
c_i = \tan(a_i) \cdot b_i - a_i^{b_i}
$$

for $i \in [0, 1234566]$

### Let's JIT it with `numba`!

## Exercise 11: Given two arrays `a` anb `b`, check if they are equal

    a = np.random.random(1234567)
    b = a.copy()

    b[-1] = 23  # artificially make them differ at the very end ;)

### Using numba?

## Exercise 12: Make a  numpy array immutable

## Exercise 13: Calculate the diagonal of a dot product

## Exercise 14: Find the most frequent value in an array

## Exercise 15: Roll two 6-sided dice 123456 times and count each individual value

## Exercise 16: Roll five 12-sided dice 123456 times and count each individual value

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).